Added motion-detection support
adafruit/Adafruit_MPU6050 pull request #6
Opened 2020-11-15 00:44 UTC by yoavw

Added support for activating motion interrupts:
- Set motion threshold
- Set duration threshold
- Set high-pass filter for motion detection
- Change interrupt latch behavior and polarity if needed
- Enable motion interrupt

Useful for waking the MCU from sleep modes, based on motion trigger.

Caveat: the MPU6050 motion-detection mode is not power efficient.  Much better than keeping the entire MCU awake, but not as efficient as I hoped.

2020-11-15 00:47 UTC, ladyada commented
nice, thank you! we'll check it out :)

2020-11-18 01:57 UTC, siddacious commented
heya @yoavw , it looks like the code is stuck on the formatting check by `clang-format`. You can see here the changes that it wants to make to the formatting:
https://github.com/adafruit/Adafruit_MPU6050/pull/6/checks?check_run_id=1401283114

While you _can_ manually make those changes, it's _much_ easier to use `clang-format` to make the changes for you. See here:
https://github.com/adafruit/Adafruit_MPU6050/pull/6/checks?check_run_id=1401283114

Including a small example that shows how the new features work would help make testing easier and is good documentation for users to know how to use it.

 thanks for your contribution!
_B

2020-11-18 01:57 UTC, siddacious requested changes
Please fix the formatting and add an example

2020-11-18 02:48 UTC, yoavw commented
@siddacious I applied the clag-format fixes, although some of the changes were in lines of code that I didn't touch.  Should be fine now.

As for an example, I no longer have the sensor to test it on, so I can't test a synthetic example.  I can paste the code I used in my project, which utilized this feature and worked well.

This is my function for using this feature:

void mpu_motion_detection(bool enable) {
    if (enable) {
        mpu.setHighPassFilter(MPU6050_HIGHPASS_0_63_HZ);
        mpu.setMotionDetectionThreshold(1);
        mpu.setMotionDetectionDuration(20);
        mpu.setInterruptPinLatch(true);	// Keep it latched.  Will turn off when reinitialized.
        mpu.setInterruptPinPolarity(true);
        //attachInterrupt(D7, motion_interrupt, CHANGE);	// Commented since we only use it for deep-sleep wakeup
    } else {
        //detachInterrupt(D7);
        mpu.setHighPassFilter(MPU6050_HIGHPASS_DISABLE);
    }
    mpu.setMotionInterrupt(enable);
}

2021-11-14 09:42 UTC, tbressers approved these changes

2021-11-14 09:42 UTC, tbressers approved these changes

2021-11-14 09:47 UTC, tbressers approved these changes

2022-02-25 01:54 UTC, gabrielcsapo commented
any update @siddacious @ladyada ?

2022-02-25 02:07 UTC, gabrielcsapo commented
@yoavw I can help run the example if you want?

2022-02-25 03:48 UTC, ladyada commented
@gabrielcsapo yeah try it out and let us know if it works!

2022-02-25 22:06 UTC, gabrielcsapo commented
@ladyada I have added an example for this in https://github.com/adafruit/Adafruit_MPU6050/pull/17. I have tested the changes and they work as expected. The interesting thing about the motion detection capabilities of the mpu6050 is that the docs are very specific on how it should be used. I linked the docs in the PR #17. Let me know fi you would like me to do anything else! 

Thanks for the changes @yoavw super interesting and really nice to have this integrated into the adafruit library for many others to use!

Also thanks for looking into this @ladyada!

2022-02-25 22:19 UTC, yoavw commented
Thanks for adding an example @gabrielcsapo !

In my own project I found it most useful as a way to wake up from deep-sleep, as mentioned in my code snippet above.  You can also use it without sleep, and react to the interrupt, but the way I used it is to keep a battery-powered project asleep, and only wake up when picked up.

2022-02-25 22:35 UTC, merged